const state={page:'dashboard',apiKey:localStorage.getItem('wr_api_key')||'demo-key',base:'',data:{}};
const nav=[['dashboard','▦','Dashboard'],['bsc','🔥','BSC 新币雷达'],['airdrops','🎁','Airdrop Radar'],['smart','🧠','Smart Money'],['whale','🐋','Whale Radar'],['tokens','🪙','Token Intelligence'],['dex','💧','DEX Radar'],['alerts','🚨','Alpha Alerts']];
const app=document.getElementById('app');
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function short(x){return x?x.slice(0,6)+'…'+x.slice(-4):'—'}
function money(x){x=Number(x||0);return x>=1e6?'$'+(x/1e6).toFixed(2)+'M':x>=1e3?'$'+(x/1e3).toFixed(1)+'K':'$'+x.toFixed(0)}
function api(path,opt={}){const url=(state.base||'')+path;return fetch(url,{...opt,headers:{'Content-Type':'application/json','X-API-Key':state.apiKey,...(opt.headers||{})}}).then(async r=>{const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d.detail||d.message||`HTTP ${r.status}`);return d})}
function layout(content){app.innerHTML=`<aside class="side"><div class="brand"><div class="logo">W</div><span>WEB3 RADAR <small>PRO</small></span></div><nav class="nav">${nav.map(n=>`<button class="${state.page===n[0]?'active':''}" data-page="${n[0]}"><i class="ico">${n[1]}</i><span>${n[2]}</span></button>`).join('')}</nav><div class="side-foot">BSC-first intelligence<br>v5.3 UI</div></aside><main class="main"><header class="top"><div class="crumb">Web3 Radar Pro / ${esc(nav.find(n=>n[0]===state.page)?.[2]||'Dashboard')}</div><div class="top-actions"><button class="btn" id="settings">⚙</button><button class="btn primary" id="refresh">Refresh</button></div></header><div class="page">${content}</div></main>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.getElementById('refresh').onclick=()=>render();document.getElementById('settings').onclick=settings}
function stat(label,val,trend='Live') {return `<div class="card"><div class="stat-label">${label}</div><div class="stat">${val}</div><div class="trend">● ${trend}</div></div>`}
async function dashboard(){let o={};try{o=await api('/api/v2/bsc/overview')}catch(e){}let a=[];try{a=await api('/api/v2/airdrops?limit=6')}catch(e){}return `<h1>Command Center</h1><div class="sub">实时观察链上机会、风险与空投状态。</div><div class="grid4">${stat('Tracked BSC pairs',o.tracked_pairs||0)}${stat('Hot tokens',o.hot||0,'Anomaly engine')}${stat('Watch tokens',o.watch||0)}${stat('Avg anomaly',o.avg_anomaly||0,'Score / 100')}</div><div class="two section"><section class="card"><div class="section-head"><h2>🔥 BSC 热门新币</h2><button class="btn" onclick="go('bsc')">View radar</button></div><div id="dash-bsc" class="loading">Loading…</div></section><section class="card"><div class="section-head"><h2>🎁 Airdrop opportunities</h2><button class="btn" onclick="go('airdrops')">Open radar</button></div>${a.length?a.slice(0,4).map(airdropMini).join(''):'<div class="empty">No seeded opportunities yet</div>'}</section></div>`}
function airdropMini(a){return `<div style="padding:12px 0;border-bottom:1px solid #18202e"><div style="display:flex;justify-content:space-between"><b>${esc(a.name)}</b><span class="badge ${a.risk_level==='low'?'low':a.risk_level==='high'?'high':'med'}">${esc(a.risk_level||'unknown')}</span></div><div class="muted" style="margin-top:4px">Potential ${a.potential_score}/100 · ${esc(a.status)}</div></div>`}
async function bsc(){let rows=await api('/api/v2/bsc/launches?limit=80');return `<h1>BSC New Token Radar</h1><div class="sub">PancakeSwap V2 PairCreated → Swap → Smart Money → Contract Risk → Anomaly Score</div><div class="card"><div class="section-head"><h2>New token feed</h2><input class="search" id="bscSearch" placeholder="Search token / address"></div><div id="bscTable">${bscTable(rows)}</div></div>`}
function bscTable(rows){if(!rows.length)return '<div class="empty">暂无数据。启动 BSC collector 后这里会持续更新。</div>';return `<table class="table"><thead><tr><th>Token</th><th>Status</th><th>Anomaly</th><th>Risk</th><th>Liquidity</th><th>Volume</th><th>Buys / Sells</th></tr></thead><tbody>${rows.map(x=>`<tr><td><div class="token">${esc(x.symbol||short(x.token_address))}</div><div class="mono muted">${short(x.token_address)}</div></td><td><span class="badge ${x.status==='hot'?'hot':x.status==='filter'?'high':'med'}">${esc(x.status||'watch')}</span></td><td><b>${x.anomaly_score??0}</b>/100</td><td>${riskBadge(x.risk_level,x.risk_score)}</td><td>${money(x.liquidity_usd)}</td><td>${money(x.volume_24h_usd)}</td><td>${x.buy_count??0} / ${x.sell_count??0}</td></tr>`).join('')}</tbody></table>`}
function riskBadge(level,score){let c=level==='low'?'low':level==='high'?'high':'med';return `<span class="badge ${c}">${esc(level||'unknown')} ${score??''}</span>`}
async function airdrops(){let [rows,cal]=await Promise.all([api('/api/v2/airdrops?limit=100'),api('/api/v2/airdrops/calendar?limit=30')]);return `<h1>Airdrop Radar</h1><div class="sub">发现机会、跟踪 Snapshot / Eligibility / Claim / Deadline，并用公开链上行为做资格启发式分析。</div><div class="cards">${rows.length?rows.map(a=>`<div class="card airdrop-card" data-airdrop="${a.id}"><div style="display:flex;justify-content:space-between"><span class="badge">${esc(a.status)}</span>${riskBadge(a.risk_level,a.risk_score)}</div><h3 style="margin-top:14px">${esc(a.name)}</h3><div class="muted">Chain ${a.chain_id} · Potential ${a.potential_score}/100</div><div class="progress"><i style="width:${a.potential_score}%"></i></div><div class="airdrop-meta"><div class="kv"><span>Snapshot</span><b>${fmt(a.snapshot_at)}</b></div><div class="kv"><span>Deadline</span><b>${fmt(a.deadline_at)}</b></div></div></div>`).join(''):'<div class="card empty">没有空投数据。运行 seed_airdrops.py 写入初始数据。</div>'}</div><div class="two section"><section class="card"><div class="section-head"><h2>📅 Airdrop Calendar</h2></div><div class="timeline">${cal.length?cal.map(e=>`<div class="event"><div><b>${esc(e.project)}</b><div class="muted">${esc(e.event)}</div></div><b>${fmt(e.at)}</b></div>`).join(''):'<div class="empty">暂无日历事件</div>'}</div></section><section class="card"><div class="section-head"><h2>🔎 Wallet Eligibility</h2></div><div class="form"><input class="search" style="flex:1" id="wallet" placeholder="0x wallet address"><button class="btn primary" id="checkWallet">Analyze</button></div><div id="walletResult"></div></section></div>`}
function fmt(x){if(!x)return '—';try{return new Date(x).toLocaleString([],{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return x}}
async function smart(){let rows=await api('/api/v1/wallets?limit=50&smart_only=true');return `<h1>Smart Money</h1><div class="sub">钱包智能评分与资金行为基础层。</div><div class="card"><table class="table"><thead><tr><th>Wallet</th><th>Chain</th><th>Score</th><th>Transfers</th><th>Whale events</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td class="mono">${short(x.address)}</td><td>${x.chain_id}</td><td><b>${x.score}</b></td><td>${x.transfers}</td><td>${x.whales}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No indexed smart-money wallets</td></tr>'}</tbody></table></div>`}
async function tokens(){let rows=await api('/api/v1/tokens?limit=80&chain_id=56');return `<h1>Token Intelligence</h1><div class="sub">价格、流动性、交易量与基础 Token 数据。</div><div class="card"><table class="table"><thead><tr><th>Token</th><th>Price</th><th>Liquidity</th><th>24h Volume</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td><b>${esc(x.symbol||'Unknown')}</b><div class="mono muted">${short(x.address)}</div></td><td>$${Number(x.price_usd||0).toFixed(6)}</td><td>${money(x.liquidity_usd)}</td><td>${money(x.volume_24h_usd)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No BSC token data</td></tr>'}</tbody></table></div>`}
async function generic(title,sub,path,headers,render){let rows=[];try{rows=await api(path)}catch(e){}return `<h1>${title}</h1><div class="sub">${sub}</div><div class="card"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(render).join(''):`<tr><td colspan="${headers.length}" class="empty">暂无数据。对应 Worker 启动后会自动填充。</td></tr>`}</tbody></table></div>`}
function settings(){const key=prompt('X-API-Key',state.apiKey);if(key!==null){state.apiKey=key.trim();localStorage.setItem('wr_api_key',state.apiKey);render()}}
window.go=p=>{state.page=p;render()};
async function render(){let c='<div class="loading">Loading…</div>';try{if(state.page==='dashboard')c=await dashboard();else if(state.page==='bsc')c=await bsc();else if(state.page==='airdrops')c=await airdrops();else if(state.page==='smart')c=await smart();else if(state.page==='tokens')c=await tokens();else if(state.page==='whale')c=await generic('Whale Radar','大额资金行为与鲸鱼事件。','/api/v1/transfers?limit=60&chain_id=56',['Wallet / TX','Token','Block','Amount'],x=>`<tr><td class="mono">${short(x.from)} → ${short(x.to)}<div>${short(x.tx)}</div></td><td class="mono">${short(x.token)}</td><td>${x.block}</td><td>${esc(x.amount_raw)}</td></tr>`);else if(state.page==='dex')c=await generic('DEX Radar','池子创建与 Swap 活动。','/api/v1/swaps?limit=60&chain_id=56',['Pair','TX','Sender','Block'],x=>`<tr><td class="mono">${short(x.pair)}</td><td class="mono">${short(x.tx)}</td><td class="mono">${short(x.sender)}</td><td>${x.block}</td></tr>`);else c=await generic('Alpha Alerts','统一信号流。','/api/v1/signals?limit=80&min_score=0&chain_id=56',['Type','Token','Wallet','Score','Reason'],x=>`<tr><td><span class="badge hot">${esc(x.type)}</span></td><td class="mono">${short(x.token)}</td><td class="mono">${short(x.wallet)}</td><td><b>${x.score}</b></td><td>${esc(x.reason)}</td></tr>`)}catch(e){c=`<h1>${esc(nav.find(n=>n[0]===state.page)?.[2])}</h1><div class="error">API Error: ${esc(e.message)}<br><span class="muted">检查 API Key、数据库和 Worker 是否正常运行。</span></div>`}layout(c);bindPageEvents()}
function bindPageEvents(){const s=document.getElementById('bscSearch');if(s){s.oninput=()=>{const q=s.value.toLowerCase();document.querySelectorAll('#bscTable tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none')}}document.querySelectorAll('[data-airdrop]').forEach(c=>c.onclick=async()=>{const d=await api('/api/v2/airdrops/'+c.dataset.airdrop);modal(`<button class="close" onclick="this.closest('.modal-back').remove()">×</button><h2>${esc(d.name)}</h2><p class="muted">${esc(d.status)} · Potential ${d.potential_score}/100 · Risk ${esc(d.risk_level)}</p><div class="airdrop-meta"><div class="kv"><span>Website</span><b>${d.official_website?`<a href="${esc(d.official_website)}" target="_blank">Official</a>`:'—'}</b></div><div class="kv"><span>Claim</span><b>${d.official_claim_url?`<a href="${esc(d.official_claim_url)}" target="_blank">Claim page</a>`:'—'}</b></div></div><h3>Tasks</h3>${(d.tasks||[]).map(t=>`<div class="event"><span>${esc(t.title)}</span><span class="badge ${t.required?'hot':'low'}">${t.required?'Required':'Optional'}</span></div>`).join('')}`)});const cw=document.getElementById('checkWallet');if(cw)cw.onclick=async()=>{const w=document.getElementById('wallet').value.trim();const out=document.getElementById('walletResult');out.innerHTML='<div class="loading">Analyzing public on-chain activity…</div>';try{const r=await api('/api/v2/airdrops/check-wallet',{method:'POST',body:JSON.stringify({address:w})});out.innerHTML=r.map(x=>`<div class="section"><div class="card"><b>${esc(x.project)}</b> <span class="badge ${x.eligibility==='likely'?'low':x.eligibility==='possible'?'med':'high'}">${x.eligibility}</span><div class="wallet-result"><div class="kv"><span>Confidence</span><b>${x.confidence}%</b></div><div class="kv"><span>Task Coverage</span><b>${x.task_coverage}%</b></div><div class="kv"><span>Activity</span><b>${x.activity_score}</b></div><div class="kv"><span>Tx Count</span><b>${x.tx_count}</b></div></div><p class="muted">${esc(x.warning)}</p></div></div>`).join('')}catch(e){out.innerHTML='<div class="error">'+esc(e.message)+'</div>'}}}
function modal(body){const d=document.createElement('div');d.className='modal-back';d.innerHTML='<div class="modal">'+body+'</div>';d.onclick=e=>{if(e.target===d)d.remove()};document.body.appendChild(d)}
render();
